* paeiot-sensor-one :TOC:
  - [[#introduction][Introduction]]
  - [[#aim][Aim]]
  - [[#whats-in-this-repository][What's in this Repository]]

** Introduction
PAE IoT LoRaWAN Sensor Module

This project is a product of the Port Adelaide Enfield Libraries IoT Experimenters
group. The groups github repository can be found at [[https://github.com/PaulSchulz/paeiot-experimenters]] 

Comments are most welcome. See the above link for the group details.

** Aim
Design and Build IoT LoRaWAN capable device which can be used for
environmental sensing.

The initial discussion paper (RFC) can be found here: [[https://github.com/PaulSchulz/paeiot-experimenters/blob/main/doc/rfc/00001-iot-lorawan-device.org][00001-iot-lorawan-device.org]]

The current project is based around the [[https://store.arduino.cc/usa/mkr-wan-1310][Arduino MRKWAN1310 board]], which uses a
SAND21 processor capable of low power operation, and a LoRa radio which allows
data logging via the LoRaWAN network.

** What's in this Repository
Subdirectories:
- Arduino - Directory containing Arduino sketches used by the project.
- [[blog/index.org][Blog]] - Progress Reports and Updates
- Images - Pictures, diagrams
